version: "3.6"

services:
  ecommerce-db:
    container_name: ${DB_NAME}
    image: mongo:6.0
    volumes:
      - app-vol:/data/db
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: pass
    # command: [ "--auth" ]

  mongo-express:
    depends_on:
      - ecommerce-db
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8080:8081
    restart: always
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: ${DB_NAME}

  ecommerce-back:
    depends_on:
      - ecommerce-db
      - mongo-express
    container_name: "ecommerce-server"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      PRIVATE_KEY: secretkey
      APPLICATION: AppExpress
      DB: MongooseAdapter
      DB_URI: mongodb://ecommerce-db:27017/
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    restart: always
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env

volumes:
  app-vol:
    external: false
